#spring.application.name=Task-Management-System
spring:
 datasource:
  url: jdbc:mysql://localhost:3306/taskmanagement
  username: root
  password: root
 jpa:
   hibernate:
     ddl-auto: update
   show-sql: true
 mail:
    host: smtp.gmail.com
    port: 587
    username: ""
    password: ""
    properties:
     mail:
      smtp:
       auth: true
       starttls:
        enable: true
            